### ISSUE TITLE
Distribución de preguntas Etica.  

### ISSUE THREAD

**Issue by PaulBlack91** [ARG-Broker-ISPC-PG/Proyecto-Integrador-ARGBroker#1]
Investigar y desarrollar las sigueintes consignas del funcionamiento de ARGBroker

· Describir cómo el grupo se conforma como instrumento legal (Empresa, Socios, CEO,
Empleados) y si tendrán un contrato con que cláusulas.

· Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la
Profesión.

**Comment by AgustinGibaut** [comment]
Describir cómo el grupo se conforma como instrumento legal (Empresa, Socios, CEO,
Empleados) y si tendrán un contrato con que cláusulas.

el grupo se puede conforma en:

### Junta Directiva:  generalmente es la encargada de la parte estratégica de la empresa. (conformado por director, gerente y los  socios)
### implementación de desarrollo:  crear software como mejorarlos
### La producción la cual es la encarga de crear y como diseñar el programa. 
### Marketing: En esta sección es importante ya que se encarga o es la responsable de las estrategias del mercado y las ventas.

> **SOCIOS**
**Los socios tienen derecho a participar en las juntas.
Los socios están obligados a cumplir con las decisiones de la Junta.**
> **CEO**
el ceo va a tener permisos para gestionar **operaciones diarias**
**BENEFICIOS**
capacitación constantes
la empresa les brindara equipos para poder realizar la actividad 

### **_Se otorga matrícula a los profesionales que poseen título habilitante_**

**Comment by PaulBlack91** [comment]
se modifica y se carga a la wiki
