### ISSUE TITLE
Asignación de actividades base de datos

### ISSUE THREAD

**Issue by PaulBlack91** [ARG-Broker-ISPC-PG/Proyecto-Integrador-ARGBroker#17]
Se asignara el proceso de resolución del apartada de base de datos a los integrates del grupo seleccionados. 

1. Identificar las entidades principales del sistema.
2. Definir los atributos para cada entidad, considerando los datos necesarios para
cumplir con las funcionalidades especificadas.
3. Establecer las relaciones entre las entidades identificadas.
4. Aplicar el proceso de normalización a las entidades y sus atributos para eliminar
redundancias y dependencias funcionales. Se debe alcanzar la Tercera Forma
Normal (3FN).
5. Crear el modelo relacional resultante de la normalización, representando las entidades
como tablas con sus respectivos atributos y relaciones. Definir las claves primarias y
foráneas necesarias para establecer las relaciones entre las tablas.
6. Documentar el diseño de la base de datos, incluyendo una pequeña descripción de
cada tabla. Y las aclaraciones que creas necesarias en cada una de ellas. Por
ejemplo si se realizó una suposición de algo que no estaba en el enunciado y eso
determinó que una relación es uno a muchos, cuando se podría haber interpretado
por una ambigüedad que podía ser muchos a muchos, dejar asentada tal suposición.

**Comment by PaulBlack91** [comment]
Se carga en wiki y readme  lo de base de datos

**Comment by dgel92** [comment]
Se gestiona grafico Entidad Relacion, se adjunta link de acceso. 
https://lucid.app/lucidchart/96ed5230-cb77-423f-aa4c-fb29b041ffcb/edit?viewport_loc=-2849%2C-1559%2C3468%2C1879%2C0_0&invitationId=inv_d0673c9d-4ebe-4b25-a102-b9bc804aaa90
